blank_issues_enabled: false
contact_links:
  - name: Question or discussion
    url: https://github.com/anthonysawah/espn-fantasy-baseball-api/discussions
    about: Ask a question, share a recipe, or propose an idea for discussion.
